<<<<<<< HEAD
image: php:7.1.1
=======
image: dotsunited/git-ftp
>>>>>>> dev
pipelines:
  branches:
    dev:
      - step:
          script:
<<<<<<< HEAD
            - echo "only on dev"
            - apt-get update
            - apt-get -qq install git-ftp
            - git config git-ftp.url "ftp://$SERVER_IP/dev/platform"
            - git config git-ftp.user $SFTP_username
            - git config git-ftp.password $SFTP_password
            - git ftp catchup
            - git ftp push -n -f
=======
            - git config git-ftp.url "ftp://$SERVER_IP/dev/platform"
            - git config git-ftp.user $SFTP_username
            - git config git-ftp.password $SFTP_password          
            - git ftp push -f
>>>>>>> dev

