apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prod-dbadmin
  labels:
    app: prod-dbadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-dbadmin      
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prod-dbadmin     
    spec:
      containers:
      - name: prod-dbadmin
        image: phpmyadmin/phpmyadmin:4.6
        env:
        - name: PMA_HOST
          value: prod-mysqlservice.default
        ports:
          - containerPort: 80
            name: prod-dbadmin
