apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prod-webserver
  labels:
    app: prod-webserver
    tier: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-webserver      
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prod-webserver        
    spec:
      containers:
      - name: php-fpm
        image: gcr.io/modern-cubist-206411/oa-php:7.1.1
        ports:
        - name: php
          containerPort: 9000
        volumeMounts:
        - name: shared-files
          mountPath: /www
        - name: php-config
          mountPath: /usr/local/etc/php/conf.custom
        env:     
        - name: PHP_INI_SCAN_DIR
          value: :/usr/local/etc/php/conf.custom
        - name: WPC_DB_NAME
          value: prod_wp
        - name: WPC_DB_USER
          value: root
        - name: WPC_DB_PASSWORD
          value: pass123
        - name: WPC_DB_HOST
          value: prod-mysqlservice.default
        - name: WPC_DB_CHARSET
          value: utf8mb4
        - name: WPC_DB_COLLATE
          value: ''
        - name: WPC_AUTH_KEY
          value: '^Ymd|0pcH_ZO=(0ur6KRx+k|lN|;ze^6XPd3mXTi+7n-3+Z{%J#)+?jS{c|RXxx:'
        - name: WPC_SECURE_AUTH_KEY
          value:  'P$iq),.5TG:omMd1VklQW$!%B+3[EYX I<GXZ=(9OzYXx61/Gn-Gm>q%; UCnkuC'
        - name: WPC_LOGGED_IN_KEY
          value: 'M3`Z Ap4=:]3x@sp}gk%iNTA]1![5(c$}8ve+cv)ubm9g26^]@9O4*/z&(.IBtF '
        - name: WPC_NONCE_KEY
          value:  'CwjI84TD#1Y`Fh(CUXN)9H/3paS&hz5n5)laOkqfI.x>pD^bVW~&dKOi.,]WZ_.j'
        - name: WPC_AUTH_SALT
          value:  ' ]j96;{dkGBjWF$/p)F&QS9%<,8/V}>E-5#./nw[S5zD,VcU%.V5~3e&9<B3&2,f'
        - name: WPC_SECURE_AUTH_SALT
          value: 'rUQ<U9WtErYQP&nPGCJ,59Zsb{aNll:Ah<e)dbX-Y>O$plvz_2PgL&`gtcxU>s$)'
        - name: WPC_LOGGED_IN_SALT
          value: '|U!)&g,,`c:1S0Ecz-yQ+e}K4XAE$.GDXpR`&I#[=t7DWXU1QW+W@nr)_q-TTiPu'
        - name: WPC_NONCE_SALT
          value: ')J<H[cwR+(5b8@F<@f;h^{FgKl(oH=UDtq]u5Sj0tZ!eQx`MAa`Y(JD,&!|,o8g]'
        - name: WPC_WP_DEBUG
          value: 'false'
        - name: WPC_WP_ALLOW_MULTISITE
          value: 'true'
        - name: WPC_MULTISITE
          value: 'true'
        - name: WPC_SUBDOMAIN_INSTALL
          value: 'true'
        - name: WPC_DOMAIN_CURRENT_SITE
          value: '1acad.me'
        - name: WPC_PATH_CURRENT_SITE
          value: '/'
        - name: WPC_SITE_ID_CURRENT_SITE
          value: '1'
        - name: WPC_BLOG_ID_CURRENT_SITE
          value: '1'
        - name: WPC_FS_METHOD
          value: 'direct'
        - name: WPC_TABLE_PREFIX
          value: 'wp_'
        - name: DEFAULT_MOODLE_PROTOCL
          value: 'https://'
        - name: FORCE_SSL_ADMIN
          value: 'true'
        - name: APP_ROOT_DIR
          value: /www
        - name: WPC_INSTALLED
          value: '1'

      - name: nginx
        image: gcr.io/modern-cubist-206411/oa-openresty:1.3.17
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: shared-files
          mountPath: /www
        - name: shared-files
          mountPath: /etc/resty-auto-ssl/letsencrypt
          subPath: ssl-certs
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", " cp -r -p /app/. /www ", "&& chown -R www-data.www-data /www/bin ", "&& cp -R /www/moodata/default_moodledata /www/moodata/lms_1acad_me_data", "&& chmod -R 755 /www/moodata/lms_1acad_me_data/"]

      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: prod-shared-files-pvc
        - name: php-config
          configMap:
            name: php-config