apiVersion: v1
kind: Service
metadata:
  labels:
    app: bbb
  name: bbb-udp
spec:
  ports:
  - name: port5b
    port: 3478
    protocol: UDP
    targetPort: 3478

  selector:
    app: bbb-udp
  type: LoadBalancer
