apiVersion: apps/v1 
kind: Deployment
metadata:
  name: bbb
  labels:
    app: bbb    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bbb      
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bbb        
    spec:
      containers:
      - name: bbb
        image: bigbluebutton/bigbluebutton
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 1935
          name: port1
        - containerPort: 5066
          name: port2
        - containerPort: 3478
          name: port3
          protocol: TCP
        - containerPort: 3478
          name: port4
          protocol: UDP
        - containerPort: 16384
          name: port5
          protocol: UDP
        - containerPort: 32768
          name: port6
          protocol: UDP
       
