apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql      
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql        
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
          name: mysql
        env:       
        - name: MYSQL_ROOT_PASSWORD
          value: pass123       
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: prod-mysql-pvc