apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prod-db
  labels:
    app: prod-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-db      
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prod-db        
    spec:
      containers:
      - name: prod-db
        image: phpmyadmin/phpmyadmin:4.6
        env:
        - name: PMA_HOST
          value: mysql.default
        ports:
          - containerPort: 80
            name: prod-db
