apiVersion: apps/v1 
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy      
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: proxy        
    spec:
      containers:
      - name: proxy
        image: gcr.io/modern-cubist-206411/oa-proxy:0.16
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
